<body>

<center>

<img src="images/WSCreditsPanel/aboutLogo.gif" /><br />

<font color="green">Game Translator - Game Language Translation Assistant</font><br />
<font color="orange">Created and Developed by WATTO Studios (c) 2006-2009<br />
<u>http://www.watto.org/trans</u></font><br />

<br /><br />

<font color="white">Game Translator is a program that edits language packs used in games. See the Readme file for further information and contact details, or visit the website.</font>

<br /><br />

<img src="images/WSCreditsPanel/softpedia.gif" /><br />
Game Translator is free from viruses, adware, and spyware.

<br /><br />

<font color="blue">Game Translator makes use of the following software packages...</font>

<br />

</center>

<ul>
<li>Java</li>
</ul>

<center>

<br />

<font color="orange">WATTO Studios wishes to thank the following...</font><br /><br />

<font color="blue">IMPORTANT PEOPLE:</font>

</center>

<ul>
<li>The computer game developers who develop wonderful games for the community.</li>
<li>SourceForge - for hosting the program and reducing the traffic on my website.</li>
<li>Sarah - For showing me everything that is important, and that I don't have to sacrifice to be happy.</li>
<li>Everyone who helps to make my life a happy and enjoyable one.</li>
</ul>

<br />

<center>
<img src="images/WSCreditsPanel/sourceforge.gif" /><br />
Game Translator is hosted on SourceForge.<br />
<u>http://sourceforge.net/projects/gametranslator</u>
</center>

</body>