<WSPanel code="SidePanel_PluginList" layout="BorderLayout">
	
	<WSComboBox code="SidePanel_PluginList_PluginTypes" position="NORTH" />
	
	<WSPanel layout="GridLayout" position="CENTER" rows="2" columns="1">

		<WSScrollPane code="SidePanel_PluginList_Plugins_Label" showLabel="true" >
			<WSList code="SidePanel_PluginList_Plugins" />
		</WSScrollPane>
		
		<WSScrollPane code="SidePanel_PluginList_PluginDescription_Label" showLabel="true" >
			<WSTextArea code="SidePanel_PluginList_PluginDescription" editable="false" wrap="true" />
		</WSScrollPane>

	</WSPanel>
	
</WSPanel>